### ISSUE TITLE
Modal focus lost :(

### ISSUE THREAD

**Issue by Errbel** [PeppeL-G/bootstrap-3-modal#10]
Hi,

The modal window shown didn't get the focus : 

![screen shot 2015-01-28 at 2 48 30 am](https://cloud.githubusercontent.com/assets/4772557/5937293/197db862-a6ee-11e4-9be2-0cb572210df5.png)

Can you please help ?

Thx
:)

**Comment by PeppeL-G** [comment]
You mean the modal is behind the element that makes the background (and in this case also the modal) darker?

**Comment by Errbel** [comment]
Yes.

**Comment by PeppeL-G** [comment]
I'm sorry, but I can't explain that behavior. And I don't think it has something to do with this package, but more likely some of your CSS that's messing it up, and I can't help you with that. All I can say is that the modal is rendered into the `<body>` element.

**Comment by Errbel** [comment]
Ok, thanks for your help, I'm checking my CSS.

**Comment by Errbel** [comment]
You're right, it seems that I had an old bootsrap CSS file !

Thanks PeppeL-G !
