### ISSUE TITLE
request set max height on modal  body?

### ISSUE THREAD

**Issue by thearabbit** [PeppeL-G/bootstrap-3-modal#11]
would I request you to create option of max height on modal body?
I have problem with the long body modal (multi modal), and i try custom like:

```
// css
.modal-body {
    overflow-y: auto;
}
// js
modalMaxHeight = function () {
    var height = $(window).height() - 200;
    $(".modal-body").css("max-height", height);
};
```

I call this after `Modal.show`.
I think that it is good, like the `Modal.allowMultiple = true`

**Comment by PeppeL-G** [comment]
I want to keep this package simple, and your suggestion is one of 1000 customization one can do, so I don't like the idea of adding it. And I won't add code for supporting multiple modals, except the ability to insert multiple modals. So, I'm sorry, but this snippet you must provide yourself.

By the way, hard coding 200 seems like a bad solution. That does not work if the user increase the font size, right?

**Comment by thearabbit** [comment]
it is clear, thanks.
