### ISSUE TITLE
Include options

### ISSUE THREAD

**Issue by jfurneaux** [PeppeL-G/bootstrap-3-modal#14]
Hi! This package is great. Is there anything stopping the inclusion of the standard Bootstrap modal 'options' object as a third parameter?

**Comment by PeppeL-G** [comment]
Thanks for the suggestion!

It was a design choice to not support options via a parameter, but it's open for discussion. My idea was to have a minimal JavaScript API that's easy to use, so I skipped the options. I thought that if one really needed them, one could pass them via the `data-` attributes, which should work fine as long as they're static, but I realize that may not be the case for everyone. Do you belong to the group of people needing to set the options dynamically?

**Comment by jfurneaux** [comment]
Thanks for your reply Peter!

I am completely in favour of simplifying things as much as possible.
Perhaps there is a way to achieve my goal without needing the options
object.

I present the modal without user interaction when a user logs in, if their
profile fields are incomplete (which happens when they first start using my
service).

I wish to prevent the user from canceling out of the modal by clicking on
the background.

Is there a way to trigger that option that I am missing. It's entirely
possible! I couldn't figure out how to use the data- option if it wasn't
triggered by a link or button. :)

Best regards,

John

**Comment by PeppeL-G** [comment]
I don't get your last paragraph, did you get it to work? Otherwise, see:

http://getbootstrap.com/javascript/#modals-options

So you want the `backdrop` option to be `"static"` and the `keyboard` option to be `false`? Then add `data-backdrop="static" data-keyboard="false"` to the root element of the modal (the element with the `modal` class).

**Comment by jfurneaux** [comment]
Ha, well that's embarrassing. I assumed that it had to be set by the calling object. All sorted, thanks so much! :)
