### ISSUE TITLE
Open modal template from another file

### ISSUE THREAD

**Issue by t3db0t** [PeppeL-G/bootstrap-3-modal#19]
Should I be able to `show` a modal template from another template file?  In other words, say I've got `deleteModal` in `main.html` and `settingsModal` in `meeting.html`.  `settingsModal` has a delete button which does `hide("settingsModal")` and then `show("deleteModal")` but I can't get it to recognize `deleteModal`.  Am I missing something?  Thank you for the terrific package!

**Comment by Maxhodges** [comment]
you should be using Modal.show and Modal.hide from event code (.js) not from HTML.

should be pretty clear in the docs
https://github.com/Maxhodges/bootstrap-3-modal

Are you new to Meteor?

**Comment by t3db0t** [comment]
Everything I described is from the js code, perhaps I was confusing.  No, I'm not new to Meteor.

Say I've got `client/meetings.html` containing `meeting` and `settingsModal` templates, and helpers/events in `client/meetings.js`.  In one of those events, I can do `Modal.show("settingsModal") and it works fine.  I also try to do`Modal.show("deleteModal")`.  The`deleteModal`template is in`client/main.html`.  It does nothing; no errors, and no modal or any apparent change at all.  I just wanted to see if it _should_, and ask what might cause it not to work.

**Comment by Maxhodges** [comment]
the modal template can be anywhere in the client code, so it _should_ work. Are you sure you named it correctly? Also are you sure it has the right sections? 

modal-header and modal-footer are optional but I think you definitely need modal-dialog, modal-content and maybe modal-body

```
<template name="deleteModal">
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-body">
                    <p>A modal example.</p>
                </div>
...
```

**Comment by Maxhodges** [comment]
if still not working please post a link to a demo repo and I'll be happy to take a look!

**Comment by PeppeL-G** [comment]
I fear that you're trying to show two modals at the same time (before the first modal has been hidden (removed), you're trying to show the second one). You have to wait for the first modal to be hidden, and then show the second one, or enable multiple modals (having `Modal.allowMultiple = true` in the your code).

At the moment you can't listen for the hidden event. This has actually been a problem for me as well, and I've thought of two solutions. The first one is that `Modal.show` returns a jQuery object containing the modal, so you can call the `on` property on it to listen for different events (and possibly do other things as well). The second one is to add an optional callback to `Modal.hide` that gets called when the modal has been hidden (removed).

The first solution is more general, but the second one requires less code from the programmer, so I haven't been able to decide which one to use, so I've been awaiting someone else to have the same trouble :) Any thoughts? Personally, I've never learned the name of the hidden event (`hidden.bs.modal`) by heart, which makes me think it might be better to go with the second solution.

**Comment by t3db0t** [comment]
@PeppeL-G, just as I started reading your comment I realized that this is indeed the case.  Can't believe I missed it.

I may try `allowMultiple`, but I'm realizing that closing a modal and opening another is kinda crappy design anyway, so I might take another approach.  I'll go ahead and close this ticket.  Thanks all!

**Comment by Maxhodges** [comment]
@t3db0t yeah, instead of open another modal, just change what you render in the current modal. That's how I do it in this phone verification "wizard"
http://screencast.com/t/8vCV6vTBk

**Comment by t3db0t** [comment]
@Maxhodges right—great example.  Is that a meteor app? Are you swapping templates within the modal?  Could you share how you're doing it?

**Comment by Maxhodges** [comment]
yes meteor app. When user clicks button just set a state variable (use the url if you want to be clever https://meteorhacks.com/meteor-ui-pattern-keeping-app-state-in-the-url), then have your helper return it, and use the helper in an if/else block in your template to swap the design  i.e. `{{#if isVerifyMode}}`

**Comment by Maxhodges** [comment]
posted a full example to the Wiki
https://github.com/PeppeL-G/bootstrap-3-modal/wiki/Delete-Confirmation-modal-example
