### ISSUE TITLE
Modal already opened

### ISSUE THREAD

**Issue by ghost** [PeppeL-G/bootstrap-3-modal#2]
First of all: "Thanks for the package".
Would it be complicated to add a Modal.isOpened(<template name>) that returns a boolean.
If by accident I click twice, or if my mouse does special tricks (sometimes) more than one instance of the modal is displayed.
I think I could check if a template named <template name> is already appended to the DOM but this add-on sounds like a nice feature to add.

Thanks again.

**Comment by PeppeL-G** [comment]
That's actually something I've experienced too.

Your suggestion could be added quite easily, but there may be a better solution. How about "don't open a dialog if there already is one open"?

**Comment by ghost** [comment]
Thank you so much for your time.
Your suggestion is exactly what I did, being very easy as I noticed that in the docs you were pointing that nothing is inserted in the DOM before Modal.show(). 
Maybe just for "api elegance" my proposal may be taken in consideration. It's obvious it's not necessary for functionality.

The important thing is that  this approach fixes the wired behaviour pointed out in my post.
Thanks again. Great package.

**Comment by PeppeL-G** [comment]
It should be fixed now, but you need to use Meteor 1.0.2 or later in order to take part of the updates.

Having a way to see if a modal is open or not may be useful, but I won't add it until someone actually needs it and can present a use case for it.

Thanks for the help!

**Comment by ghost** [comment]
Thank you too for your time and your work. 
You are right about the method. I already have Meteor updated so I’ll just update and omit the verifying code.

All the best,

Vlad Blindu
vlad.blindu@gmail.com
