### ISSUE TITLE
TypeError : $modal.modal is not a function

### ISSUE THREAD

**Issue by pwldp** [PeppeL-G/bootstrap-3-modal#20]
When I call I got an error:
`TypeError: $modal.modal is not a function peppelg_bootstrap-3-modal.js:71:3`

I use http://bootswatch.com/yeti/ package.
Whats wrong?

**Comment by Maxhodges** [comment]
going to have to give us a bit more context. Share some of your code or ideally submit a link to a repo which reproduces the problem.

**Comment by pwldp** [comment]
The repo which reproduces the problem: https://github.com/pwldp/meteor-modal-error

**Comment by PeppeL-G** [comment]
You need to add the JavaScript file for bootstrap yourself. Have you done that?

**Comment by pwldp** [comment]
Yes, it is: https://github.com/pwldp/meteor-modal-error/blob/master/modal-window.html#L11
Is this enought?

**Comment by PeppeL-G** [comment]
Oh, so that's how you add it. I'm sorry, I missed that, but unless I'm mistaking you can't load JavaScript files like that in Meteor. At least not yet, I think you'll be able to in the next version. See https://github.com/meteor/meteor/issues/4415

**Comment by pwldp** [comment]
Thanks for your help.
I put script load in <head> section and it works.
