### ISSUE TITLE
How to open the modal from within a partial template

### ISSUE THREAD

**Issue by Rongky** [PeppeL-G/bootstrap-3-modal#22]
Hi. Thanks for this package!!!

Just a question: How can one now call/load the modal from within a partial template or from a certain div like the example from the link below: 

```
http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_modal_sm&stacked=h
```

I have a main page with several partial templates and I'm using modals to insert/update data specific to those templates. So, loading these modals from within the partial template where it was called and not in the middle of the screen would give users better guide and functionality. This is true for those using 
larger/wider screen sizes.

Thanks in advance.

**Comment by PeppeL-G** [comment]
I don't entirely understand what you mean with "partial template". You don't want the backdrop to cover the entire screen, but only a part of it (e.g, restricted to a `<div>`)? That's not a feature included in bootstrap modals, but the way w3school has solved it is by showing the modal in an iframe. I don't know how well that solution fits with Meteor and this package though, but feel free to try and get it to work.

**Comment by Rongky** [comment]
This feature can easily be implemented without any additional hacks in meteor. I have already been using this in my present project with bootstrap & autoform. Simply doing {{> myModalTemplate}} anywhere in any div and calling it with $('#myModal').modal('show'), loads the modal within that div restricting the backdrop to that div. However, this approach simply inserts all modals into the DOM by default and I'm bothered with too many modals hidden at startup. But now, with your package, I only get to insert these modals after a click event. Thanks for that. Anyway, just need to find some workarounds.

Again, thanks.
