### ISSUE TITLE
How do i detect if a modal has been closed?

### ISSUE THREAD

**Issue by KnutSv** [PeppeL-G/bootstrap-3-modal#25]
If the user clicks outside the modal window, the modal closes, but I can't figure out how to detect this.

**Comment by PeppeL-G** [comment]
You can use the destroyed callback, but you don't know if the user click outside the modal window of if the model closed for some other reason. Is it possible to distinguish this in Bootstrap?

**Comment by KnutSv** [comment]
Thanks for the quick reply. Thankfully I didn't need to know how the modal was closed specifically.

Being fairly new to meteor I didn't think to use the destroyed callback. But it worked like a charm :)

For other people looking at doing something similar, the code looks like this:

``` javascript
Template.myModal.destroyed = function() {
    console.log('window closed');
}
```
