### ISSUE TITLE
Modal is not defined 

### ISSUE THREAD

**Issue by Gardezi1** [PeppeL-G/bootstrap-3-modal#28]
I am getting this error. Can you tell me why am I getting this error 

> W20151201-17:33:10.472(5)? (STDERR) 
> W20151201-17:33:10.472(5)? (STDERR) /home/kwanso/exampleModal/.meteor/local/build/programs/server/app/exampleModal.js:85
> W20151201-17:33:10.473(5)? (STDERR)         Modal.show('exampleModal');                                    // 84
> W20151201-17:33:10.473(5)? (STDERR)         ^
> W20151201-17:33:10.476(5)? (STDERR) ReferenceError: Modal is not defined
> W20151201-17:33:10.476(5)? (STDERR)     at [object Object]._onTimeout (exampleModal.js:84:9)
> W20151201-17:33:10.477(5)? (STDERR)     at Timer.listOnTimeout [as ontimeout](timers.js:121:15)
> => Exited with code: 8

**Comment by PeppeL-G** [comment]
I guess there are two possible reasons:
1. You don't include the package.
2. You include the package, but your code is executed before the code in the package has been executed.

**Comment by Gardezi1** [comment]
the first is not possible since I have included but the second may be the possibility but the thing is this error comes then the server restarts itself and then again it throws the error

**Comment by Gardezi1** [comment]
I am showing it like this 

```
Meteor.startup(function(){
    // Show the example modal 3 seconds after startup.
    setTimeout(function(){
        Modal.show('exampleModal')
    }, 3000)
})

```

**Comment by PeppeL-G** [comment]
Aha, your executing the code on the server. This package does only add the code to the client, so make sure that your code is only executed on the client.

**Comment by Gardezi1** [comment]
but you have also written the code in the startup

![selection_001](https://cloud.githubusercontent.com/assets/13199724/11501472/3404a678-9856-11e5-8a82-0f6a32be9825.png)

**Comment by Gardezi1** [comment]
oh I see what I was doing wrong. Thanks for the help
