### ISSUE TITLE
problem with mutiple level on modal?

### ISSUE THREAD

**Issue by thearabbit** [PeppeL-G/bootstrap-3-modal#3]
I try to use modal in modal (2 level), it dont work.
pl help me.

**Comment by PeppeL-G** [comment]
As it says in [the documentation](http://getbootstrap.com/javascript/#modals), bootstrap only allows one modal at a time to be shown: _Be sure not to open a modal while another is still visible. Showing more than one modal at a time requires custom code._ So you can't nest modals.

**Comment by thearabbit** [comment]
very thanks, i used to use `bootbox`, it is ok.

**Comment by yuomtheara** [comment]
now i try, it is work fine for modal on modal (multi level popup).
