### ISSUE TITLE
Modal size problem

### ISSUE THREAD

**Issue by luixal** [PeppeL-G/bootstrap-3-modal#30]
Hi, I'm having some issues when trying to show a large or small modal using `.modal-lg` or `.modal-sm`.

I'm working with this example:

``` html
<div class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">{{title}}</h4>
      </div>

      <div class="modal-body">
        {{> quickForm collection=this.collection._name id="modalForm" type=operationType doc=this.data}}
      </div>

      <div class="modal-footer" style="display:none"></div>

    </div>
  </div>
</div>
```

And it renders kind of "cut out" of the screen.

Any idea?

**Comment by PeppeL-G** [comment]
To debug this, try replacing `{{> quickForm collection=this.collection._name id="modalForm" type=operationType doc=this.data}}` with `Hello`. If it renders correct now, then we know the problem has something to do with `quickForm`.

**Comment by luixal** [comment]
Just tried and keeps happening. Modal is rendered on the left side of the page when using `modal-lg` and even more to the left when using `modal-sm`.

It's kind of difficult to explain, it's like a **huge** margin or padding was set on the right side. No clue where to look for the problem.

**Comment by PeppeL-G** [comment]
To which element do you add the `modal-sm`/`modal-lg` class?

**Comment by luixal** [comment]
Great point, that was the problem!

I was adding the modal-lg class to the first div. If I add it to the second one it works like a charm. I'll leave an example here in case anyone gets here:

``` html
<div class="modal fade">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">

      <div class="modal-header">
        <h4 class="modal-title">{{title}}</h4>
      </div>

      <div class="modal-body">
        {{> quickForm collection=this.collection._name id="modalForm" type=operationType doc=this.data}}
      </div>

      <div class="modal-footer" style="display:none"></div>

    </div>
  </div>
</div>
```

Thanks!

**Comment by ivan133** [comment]
I confirm this helps 
Also, the bug happens if you add to modal classes.

```
    <div class="modal fade" id="CommercialRentalForm_Modal_View" role="dialog" data-backdrop="false" data-keyboard="static">
        <div class="modal-dialog modal modal-lg">
```

instead of:

```
    <div class="modal fade" id="CommercialRentalForm_Modal_View" role="dialog" data-backdrop="false" data-keyboard="static">
        <div class="modal-dialog modal-lg">
```
