### ISSUE TITLE
Does not work properly with autoform

### ISSUE THREAD

**Issue by thsowers** [PeppeL-G/bootstrap-3-modal#32]
It appear that this package can interfere and cause strange behavior with autoforms that are nested in the modal. Errors range from getting an "id not found" message from the autoform library, to having the auform load with no labels or types.

For a while, it was working without incident, but as soon as I added another form to another modal, I couldn't even get the first one to work. Autoforms work fine anywhere else in the app. This includes the autoform and quickform tags

**Comment by PeppeL-G** [comment]
I don't think you're the first one to come across problems using this package together with the autoform package. I don't know anything about that package, and unfortunately I don't have time to take a look at it. 

However, this package is really small (just the [main.js](https://github.com/PeppeL-G/bootstrap-3-modal/blob/master/main.js) file), so perhaps the guys working with the autoform package can try to figure out the problem?

**Comment by Maxhodges** [comment]
been using it in multiple places with autoform in production for 6 months. haven't had these problems perhaps you're having another problem? share a repo which reproduces the problem?

**Comment by goncalovelosa** [comment]
I'm using it to update some forms, whenever i need to use the autoform hooks the validations stop working and the submission also does nothing

**Comment by thsowers** [comment]
I was eventually able to get this fixed in my application. Some of the quirky behavior I noticed is that some autoform defaults get lost when the autoform is submitted (such as a checkbox being checked by default). I was able to just use some jquery in the form hooks to get around these issues. Thanks for the package!
