### ISSUE TITLE
Unable to hide Modal opened from another Modal

### ISSUE THREAD

**Issue by cormip** [PeppeL-G/bootstrap-3-modal#34]
**Template opens Modal1:**

``` javascript
Template.items.events({
    'click .btnItemSearch': function (event) {
        Modal.show('modalSearchItem');
    }
});
```

**Modal1 opens Modal2 and hides itself. (this works)**

``` javascript
Modal.allowMultiple = true;

...

Template.modalSearchItem.events({  
    'click button.add-item': function (evt, template) {
            evt.preventDefault();
            Session.set('selectedItemId', this._id);
            Modal.hide('modalSearchItem');
            Modal.show('modalEditItem');
        }
    }
});
```

**Modal2 attempts to hide itself and nothing happens. No errors either.**

``` javascript
Template.modalEditItem.events({
    'click button.save-item': function (evt, template) {
        evt.preventDefault();
        var item = { 
            "_id" : $('#formItemId').val(), 
            "itemName" : $('#formItemName').val()
        };
        // Modal.hide('modalEditItem'); // <<< Does not work here either
        Meteor.call('saveItem', item, function (error, result) {
            if (error) {
                alert(error.reason);
            } else {
                console.log('SUCCESS'); // <<< I see this logged
                Modal.hide('modalEditItem'); // <<< Nothing happens, modal stays visible, no console error messages
            }
        });
    }
});
```

**NOTE:** if the base template calls the 2nd modal directly, the second modal DOES correctly hide itself as expected.

**Comment by PeppeL-G** [comment]
The readme:

> To remove a modal, you need to pass the modal's template instance as the first argument to `Modal.hide`.

At the moment you're passing the string `modalSearchItem` and the string `modalEditItem`, which is wrong.

**Comment by cormip** [comment]
OK. I understand. However, your own example contradicts the readme and simply uses `Modal.hide();`, which does not work in my case. The easy fix (since the code is in a template helper): `Modal.hide(template);`

**Comment by PeppeL-G** [comment]
The example using `Modal.hide()` is for the original indented usage (only allowing one modal at a time to be shown).
