### ISSUE TITLE
$modal.modal is not a function

### ISSUE THREAD

**Issue by jowilhnson** [PeppeL-G/bootstrap-3-modal#36]
Not sure what I'm doing wrong here. I've used this package in a few projects, but just decided a small project needed 1 modal and added the package to it, wrote up a modal like normal, and it won't show. I'm using the nemo64:bootsrap package, same as I've used in other projects in combination with this modal package.

Any ideas what might cause this? Problem is with this line of code: `$modal.modal(options ? options : {})`

I'm not passing options, just: `Modal.show('dataConfirmModal',fileObj);` and the data object doesn't make a difference, same error when just calling `Modal.show('dataConfirmModal');`

Helpers within the modal run, but it doesn't show.

**Comment by jowilhnson** [comment]
Nevermind. My own fault. Started digging through bootstrap, less files, etc. And realized modals weren't enabled in my custom.bootstrap.json file. Ridiculous of me.

**Comment by ladaposamuel** [comment]
I am facing this issue

**Comment by PeppeL-G** [comment]
@ladaposamuel I don't know what's wrong, but you can try to verify that:

1. You've properly installed the package (does `Modal` show anything in the console after the page has loaded?).
2. You've properly loaded Bootstrap (does `$().modal` show anything in the console after the page has loaded?)?

**Comment by ladaposamuel** [comment]
Thank you for your response, this is a sample of the error i get.
```
peppelg_bootstrap-3-modal.js?hash=27b1778e32f5f4bf3ed8787529b8e869acb1c59d:67 Uncaught TypeError: $modal.modal is not a function
    at Object.show (peppelg_bootstrap-3-modal.js?hash=27b1778e32f5f4bf3ed8787529b8e869acb1c59d:67)
    at Object.click a[href="#addNewSeller"] (sellers_list.js:7)
    at blaze.js?hash=adc5286b78e5c0f8e7f56a602f77eefb5def6bf1:3818
    at Function.Template._withTemplateInstanceFunc (blaze.js?hash=adc5286b78e5c0f8e7f56a602f77eefb5def6bf1:3769)
    at Blaze.View.<anonymous> (blaze.js?hash=adc5286b78e5c0f8e7f56a602f77eefb5def6bf1:3817)
    at blaze.js?hash=adc5286b78e5c0f8e7f56a602f77eefb5def6bf1:2617
    at Object.Blaze._withCurrentView (blaze.js?hash=adc5286b78e5c0f8e7f56a602f77eefb5def6bf1:2271)
    at Blaze._DOMRange.<anonymous> (blaze.js?hash=adc5286b78e5c0f8e7f56a602f77eefb5def6bf1:2616)
    at HTMLAnchorElement.<anonymous> (blaze.js?hash=adc5286b78e5c0f8e7f56a602f77eefb5def6bf1:863)
    at HTMLDivElement.dispatch (jquery.js?hash=6371a31efcc37d961a979ba4fa4469294df265ed:4721)


```

**Comment by PeppeL-G** [comment]
The package seem to be loaded, but can you please do `2.` for me?

**Comment by ladaposamuel** [comment]
I am 100% sure I'm loading bootstrap , bootstrap 4 precisely .

<img width="921" alt="screenshot 2018-11-06 at 6 18 09 am" src="https://user-images.githubusercontent.com/9302799/48044351-c533a500-e18b-11e8-863e-dcc8920d202d.png">

**Comment by ladaposamuel** [comment]
It seems to work now, Ive installed a jquery package already inside meteor and unknowingly i was importing another here in the footer.
THank you very much for your help and for this package.
