### ISSUE TITLE
Focus fires only on first load

### ISSUE THREAD

**Issue by ghost** [PeppeL-G/bootstrap-3-modal#4]
I don't know if this is a Modal problem or a Blaze problem but this is where I noticed that having either an 
Input element with autofocus or even setting focus() directly on an input element, works only the first time the window opens. 
Thank you for your time.

**Comment by PeppeL-G** [comment]
I think I once read that elements inserted dynamically (as in Meteor) shouldn't use the autofocus attribute, and when I search for that source now, I come across a lot of sources saying something like "the element should automatically get focus **when the page has been loaded**". In Meteor, no templates has been inserted when the page has been loaded, so I don't know how browser will handle dynamically inserted elements with the autofocus attribute.

I also think only one element is allowed to have the autofocus attribute, so that may be the reason it only works once for you (but I guess this may vary from browser to browser).

But to give the element focus in the rendered callback doesn't work neither? That surprises me. Perhaps it has something to do with bootstrap animating the modal into the view?

I can't investigate this further at the moment, but will try to look closer at it soon.

**Comment by PeppeL-G** [comment]
Seems like different browsers handle the autofocus on dynamically inserted elements differently and no standard exists. However, I just published a new version of the package where an element with the autofocus attribute will get focus when the modal is shown (via pure JavaScript).

**Comment by ghost** [comment]
Hello,

Sory for the late reply. I am a hobby app dev and sometimes I can’t keep the rithm.
Thanks again for your time and your effort.

It’s something about Meteor rendering only once a template if there’s no refresh needed. But this internal wizardry is way beyond my understanding.
I’ll update to this version and I’ll keep an eye on every upgrade.

Thanks again.
Vlad Blindu
vlad.blindu@gmail.com

**Comment by PeppeL-G** [comment]
It's true that if you change the data context, the template's `rendered` callback won't fire. Do you have "steps" in your modal? Something like the following?

``` html
<template name="myModal">
    {{#if isStep 1}}
        <input type="text" autofocus="true" name="name">
    {{/if}}
    {{#if isStep 2}}
        <input type="text" autofocus="true" name="phone">
    {{/if}}
    {{#if isStep 3}}
        <input type="text" autofocus="true" name="email">
    {{/if}}
</template>
```

Then you need to manually focus the textfield when the step change.

**Comment by ghost** [comment]
Hi PeppeL-G

In fact, I’m using auto form mainly to generate CRUD forms and this might be a problem while the input element is in a second level template.
I put the attar to autofocus=autofocus and also by targeting through JQuery an applying a focus() function.
It fires only on first load.
What’s more bizarre is that it fires once for all forms.(I’m using the same form for insert and update), so it’s definitely about the {{> quickField}} directive which doesn’t render for each modal call.
And it’s also strange as the Modal removes the element from the DOM so it should act every time as a “first load”, unless blaze keeps a rendered version in the cash.

Thanks a lot.

Vlad Blindu
vlad.blindu@gmail.com

**Comment by PeppeL-G** [comment]
I've no experienced of autoform, but using nested templates should not be a problem. For example, the following should work:

``` html
<template name="myModal">
    {{> myFormTemplate}}
</template>

<template name="myFormTemplate">
    <input type="text" autofocus="true">
</template>
```

But perhaps autoform do something more complicated that mess things up? Can you post some relevant code?

Your using Chrome, right? I've read that autofocus only works once in Chrome.

**Comment by ghost** [comment]
Hello again,
Now I’m so sorry I wasted your time. I never suspected it’s a Chrome problem. It’s the best dev environment, thought has this incredible bug.
I tested in Safari and it works perfectly.  I am very sorry I posted this issue without checking on another browser before. I was trusting Chrome blindly. this won’t happen again.
There’s no need to post code as the problem is obviously a Chrome issue not one that concerns the modal package.
I hope it might help other “idealists” like me , get back on the ground.
Thanks a lot again,

Vlad Blindu
vlad.blindu@gmail.com

**Comment by PeppeL-G** [comment]
Don't worry about wasting my time; I'm unemployed at the moment :P 

I don't think it's a bug in Chrome. I think the behavior of dynamically added elements with autofocus isn't specified anywhere, so it's just the way the Chrome developers have chose it to work. However, [this line of code](https://github.com/PeppeL-G/bootstrap-3-modal/blob/master/main.js#L46) should make it work anyway (it works in my small tests in both Chrome and Firefox), so I find it strange that it doesn't work for you.

**Comment by ghost** [comment]
I bet you won’t be for long considering your knowledge, but anyway telling me this made me want ti share with you an idea of mine.
Here it is:

I run a postproduction studio for 18 years in Bucharest Romania and even if I graduated in computer science I passed my last 22 years of my life writing music or doing all sort of composition tasks both 2D and 3D.
Right now I’m trying, in my spare time, to build, slowly, an application dedicated to ;post-production studio management.
All alternatives on the market are very expensive and for a smaller business like mine (6 people) we’d better buy some equipment instead of investing into software. (Writke is good enough).
On the other hand we work with some big clients as Peugeot or Citroen and they have a a real problem in media asset management. They loose their footage, never know what media has been used in last’s year campaign or where’s the video they need to remake a presentation. So we have to keep their media organised because if we don’t we are the one having problems when they require to have something on air in 24 hours. And by not having a dedicated app, we provide this for free. Also, they want to be involved in the production stream but they won’t come over at the studio because they are very busy, so we upload on the ftp server, they download, send emails, we modify, send email, ftp again…..you get the picture.
There are some collaborative apps n the market but either they are very expensive either they require installing software on the client’s machine, and considering their internal IT policies, this comes out of question.

So I think I might have spotted a gap on the market.  I’m not a marketing specialist but I have some idea this considering my over 20 years of experience in advertising.

I’ m trying  to build slowly an app that would take care of all this aspects, being someone  that has consistent knowledge about post-production and client service in this area and a little app development which I’m trying to improve, but it’s very hard being also the father of 4 kids. 

I definitely can’t afford hiring a software specialist to set this up at the moment  but if  you find anything interesting in my story, drop a line.

Sorry for the long story, but you said I shouldn’t worry :)

All the best,

Vlad Blindu
vlad.blindu@gmail.com
