### ISSUE TITLE
callback?

### ISSUE THREAD

**Issue by jupiterkenji** [PeppeL-G/bootstrap-3-modal#41]
Could we show the modal, where user can click on buttons to make their selection.
Then I need to use this selection from the caller code to set value.

I was hoping I can pass callback like so:

Modal.Show('mydialog', function() {
   Meteor.calls('SetDialogValue', session.get('getMyDialogSetValue'));
});

Any clue?

Thank you, great package!

**Comment by PeppeL-G** [comment]
At the moment, you can't do anything like this. However, when you show the modal you can pass it a data context. In this data context you should be able to add "callbacks" you can call manually from your event handler in the template for the modal.

Are you with me?

**Comment by jupiterkenji** [comment]
Nice! you are spotted on. I don't know we can pass callback function to data-context!!! Awesome package!
