### ISSUE TITLE
Possible to use escape key to hide modal?

### ISSUE THREAD

**Issue by Broham** [PeppeL-G/bootstrap-3-modal#42]
It looks like the default settings of `keyboard=true` should allow this, but it doesn't seem to be working.  I also tried manually setting `keybaord=true` and passing that in, but it still doesn't work.  Any idea how I can get this working?

**Comment by PeppeL-G** [comment]
I can confirm that this does not work with the sample modal shown in the README file. However, simply adding the attribute `tabindex="-1"` makes it work.
