### ISSUE TITLE
Data in rendered modal not updating reactively

### ISSUE THREAD

**Issue by pasharayan** [PeppeL-G/bootstrap-3-modal#5]
On rendering a modal with a data source, I'm finding that when the underlying data source changes, the information in the modal is not updating reactively.

For example, on running

``` javascript
Modal.show( 'detailedTaskModal' , Tasks.findOne(taskId) );
```

Which shows a modal of 

``` html
<div>{{title}}</div>
```

And then doing a simple update like this: 

``` javascript
Tasks.update( id , {title: "newer description"} );
```

does not update the title field to the newer description. Instead it continues to show the old description. When you exit and re-open the modal though, the data is updated.

I'm wondering if there's any way to make the data passed into the argument reactive again? Is it that I'm passing a variable thats to be copied instead of a data source that Blaze.renderWithData can reactively update with?

Cheers!

**Comment by PeppeL-G** [comment]
You're right; `Tasks.findOne(taskId)` is no reactive data context. You should use `function(){ return Tasks.findOne(taskId) }` if you want a reactive data context. However, I haven't thought about this, so everything may screw up now :P But try wrapping it in a function, and please let me know if that doesn't work.

**Comment by pasharayan** [comment]
Worked perfectly! Want me to write a little ammendum to your readme for that? Otherwise thanks so much!

**Comment by pasharayan** [comment]
Quick question @PeppeL-G is there any documentation on the meteor api to explain why the return function would make it reactive? I can't seem to find anything on the docs - and I'm new to Meteor in general. Thanks!

**Comment by PeppeL-G** [comment]
Oh, the docs actually specifies that the `data` parameter to `Template.dynamic` should be an object (and not alternatively a function)? Well, then I guess I've been lucky :P But I think `Template.dynamic` uses [Blaze.renderWithData](http://docs.meteor.com/#/full/blaze_renderwithdata) under the hood, and the docs says the following about that data context: "The data context to use, or a function returning a data context. If a function is provided, it will be reactively re-run.". I guess the documentation for `Template.dynamic` is incomplete. I'll create an issue about it, and if they update their docs, I find no reason to update the docs for this package.

**EDIT**

And here's the created issue: https://github.com/meteor/meteor/issues/3542#issue-55310359

**Comment by grmmph** [comment]
#33

**Comment by jowilhnson** [comment]
I've found the information in this issue to be incredibly useful, but was having problems with it sometimes working and sometimes not. I finally figured out why, and while it is probably blindingly obvious to many, it tripped me up so I thought it might help someone else at some point. 

I have had multiple instances where I decided to change an existing modal to be reactive. Some of these the modal was previously being opened like 

```
Modal.show('modalName',this)
```

 I find I often just pass 'this' as the data context to my modals. 

So to change it to be reactive, I'd just change it to

```
Modal.show('modalName', function(){return Collection.findOne({_id:this._id})});
```

and then be dumbfounded when the data was undefined in my modal. 

Moral of the story, don't use 'this._id'. Even just assigning 

```
theID = this._id;
```

and then using 

```
Collection.findOne({_id:theID});
```

will work, but using this._id directly does not.

**Comment by grmmph** [comment]
Or use ecmascript 6 and use:

```
Modal.show('modalName',() => {return Collection.findOne({_id:this._id})});
```

Or save the collection query and pass the template context:

```
Modal.show('modalName',() => { return this });
```

**Comment by PeppeL-G** [comment]
@grmmph, I don't think your second solution will make it reactive. As I understand it, once a document has been fetched from a collection, it's an ordinary JavaScript object without any reactivity.

**Comment by grmmph** [comment]
@PeppeL-G Absolutely right.
