### ISSUE TITLE
can not pass data to update of autoform.

### ISSUE THREAD

**Issue by thearabbit** [PeppeL-G/bootstrap-3-modal#6]
can not pass data to update of autoform:

``` js
// Template
<template name="companyUpdateModal">
    <div class="modal fade">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">Company Update</h4>
                </div>

                {{#autoForm collection=Collection.Company id="companyUpdate" doc=data type="update"}}

  ....................................
// When click on update btn with id
'click #update': function (e) {
        var id = this._id;
        Modal.show('companyUpdateModal', function () {
                return {data: Collection.Company.findOne(id)};
            }
        );
    }
```

Please help me.

**Comment by PeppeL-G** [comment]
I don't know how autoform works, but I can't see anything wrong you've done using this package. Please verify that the data context is correct by replacing

``` javascript
function () {
    return {data: Collection.Company.findOne(id)};
}
```

with

``` javascript
function () {
    console.log(id, Collection.Company.findOne(id))
    return {data: Collection.Company.findOne(id)};
}
```

and check the console if the expected values are logged. If they are, replace

``` html
<h4 class="modal-title">Company Update</h4>
```

with

``` html
<h4 class="modal-title">Company Update {{data._id}}</h4>
```

and check if the document's id is shown in the modal.

**Comment by thearabbit** [comment]
i try with `Session` like this:

``` js
Template.companyUpdateModal.helpers({
   data: function(){
      return Session.get('data');
   }
});
...............................
'click #update': function (e) {
        var id = this._id;
        Session.set('data', Collection.Company.findOne(id));
        Modal.show('companyUpdateModal');
    }
```

It work fine (don't understand).

**Comment by PeppeL-G** [comment]
Yea, that is strange. One thing that may have caused your first attempt to not work is if you had a helper named `data` in the `companyUpdateModal` template. The helper `data` would take precedence of the data context property named `data`.

**Comment by thearabbit** [comment]
is it good solution or not?
but i try to test autform update like this with iron router data for update, it work fine (don't use session).

```
Router.route('/items/:_id', function () {
  var item = Items.findOne({_id: this.params._id});
  this.render('ShowItem', {data: item});
});
```

**Comment by PeppeL-G** [comment]
The way you have solved it kind of abuses the `Session` object, so it's not optimal. Do you have a repository where I can take a look at your code? Or can you create a small reproduction I can debug? That's kind of the only way I can help you, cause I don't know what's wrong.

**Comment by thearabbit** [comment]
Now it is ok, after i install new meteor and test only `modal` and `autoform`. maybe problem with other package .
Very thanks for your helping.
